### ISSUE TITLE
crash with 1.18.2

### ISSUE THREAD

**Issue by hellidox** [Declipsonator/Meteor-Tweaks#12]
[latest.log](https://github.com/Declipsonator/Meteor-Tweaks/files/8182073/latest.log)
game doesnt crash when no tweaks

game does crash when yes tweaks

**Comment by Declipsonator** [comment]
A few questions:
1. What you sent is a log, if a crash report was generated it would be helpful if you can send it.
2. What version of Minecraft is this on (if it is 1.18.2 I'll make a new release for it tommorow)

**Comment by Declipsonator** [comment]
Oh wait I just read the title lmao

**Comment by hellidox** [comment]
me when

**Comment by Declipsonator** [comment]
Fixed in 1.1.8
