### ISSUE TITLE
Crash when critical hitting entities. (Particle Related?)

### ISSUE THREAD

**Issue by OCsonic** [Declipsonator/Meteor-Tweaks#14]
**Describe the bug**
When critical hitting entities the game crashes.

**To Reproduce**
Join any server.
Critical hit a entity (or use a sword or axe)
Negative Profit

**Expected behavior**
Things to proceed as normal

**Log**
https://crashy.net/r30IDWfP4ibzLycUX91C

**Desktop**
 - OS: Linux (Stock Kernel)
 - Meteor Version: 0.4.8-1445
 - Tweaks Version: 1.1.9

**Comment by OCsonic** [comment]
Also yes I know my mod list is a disaster.

**Comment by Declipsonator** [comment]
The problem here is that tanuki overwrites tweak's confetti, I'll release a fix later today.

**Comment by OCsonic** [comment]
thank you

**Comment by Declipsonator** [comment]
Fixed
