### ISSUE TITLE
Add an option for the default scaffold

### ISSUE THREAD

**Issue by I-Got-You-Dead** [Declipsonator/Meteor-Tweaks#16]
Just add a new module or a option to use default scaffold.

**Comment by Declipsonator** [comment]
What is default scaffold

**Comment by I-Got-You-Dead** [comment]
like the scaffold you get with no addons aka the "default"

**Comment by Declipsonator** [comment]
With vertical and horizontal range set to 1, scaffold is pretty much the exact same as meteor's

**Comment by I-Got-You-Dead** [comment]
k but you cant go down by sneaking :l

**Comment by Declipsonator** [comment]
Ah, you should've said that, I may move that to a mixin then to increase functionality. I do not have plans to separate modules though so I will close this issue.
