### ISSUE TITLE
as of the latest version of meteor tweaks, freecam is unable to move, and all controls move the actual player instead

### ISSUE THREAD

**Issue by BookWyrm114** [Declipsonator/Meteor-Tweaks#3]
I don't have any crash logs for this, as it causes no crash, just messes up freecam

**Comment by Declipsonator** [comment]
Oh somehow I deleted "@ EventHandler" in FreecamMixin before building, I'll put out a new release soon.

**Comment by The-Nyla** [comment]
Thanks!

**Comment by Declipsonator** [comment]
Just updated the jar in 1.0.8, should work fine now
