### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Lawerencium** [Declipsonator/Meteor-Tweaks#5]
**Describe the bug**
Crashes at startup

**To Reproduce**
1. Load the latest release of the addon
2. Start the game

**Expected behavior**
Opening Minecraft

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Meteor Version [0.4.8 DEV 1415]
 - Tweaks Version [1.1.1]
**Additional context**
``Mixin prepare for mod meteor-tweaks failed preparing BlockMixin in tweaks.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'me.declipsonator.meteortweaks.mixins.BlockMixin' was not found``

**Comment by Declipsonator** [comment]
Fixed (Just download 1.1.1 again)
