### ISSUE TITLE
Better ElytraFly

### ISSUE THREAD

**Issue by Twelve0001** [Declipsonator/Meteor-Tweaks#7]
Suggestion, not a bug. The current ElytraFly modes on Meteor are quite bad, for my taste, at least. It'd be cool if I could see a Meteor add-on include a better ElytraFly mode that feels more Vanilla? Like, Instead of immediate acceleration, make the acceleration to full speed more gradual? I think Wurst has an ElytraFly mode like this, but I'm not too sure because I haven't used Wurst in ages.

**Comment by Declipsonator** [comment]
Gradual Acceleration in ElytraFly added in v1.1.7

**Comment by Twelve0001** [comment]
thank
